name: Build and Upload Artifacts

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Build for all platforms
        run: |
          make compile

      - name: Upload Linux ARM binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-linux-arm
          path: bin/deraph-linux-arm

      - name: Upload Linux ARM64 binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-linux-arm64
          path: bin/deraph-linux-arm64

      - name: Upload Windows ARM binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-windows-arm
          path: bin/deraph-windows-arm.exe

      - name: Upload Windows ARM64 binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-windows-arm64
          path: bin/deraph-windows-arm64.exe

      - name: Upload Windows AMD64 binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-windows-amd64
          path: bin/deraph-windows-amd64.exe

      - name: Upload Darwin ARM64 binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-darwin-arm64
          path: bin/deraph-darwin-arm64

      - name: Upload Darwin AMD64 binary
        uses: actions/upload-artifact@v3
        with:
          name: deraph-darwin-amd64
          path: bin/deraph-darwin-amd64
